## Loading Text file data with Numpy

In [28]:
import numpy as np
# NumPy's loadtxt()

In [29]:
x = np.loadtxt('data.txt')
x

array([[ 23.  ,  33.  ,  45.  ],
       [ 45.  ,  76.  ,  78.  ],
       [ 45.1 ,  77.  ,  88.  ],
       [ 45.  ,  54.6 ,  88.9 ],
       [ 67.  ,  55.  ,  66.  ],
       [  5.6 ,  78.  ,  98.  ],
       [  6.55,   7.88,  33.  ],
       [ 34.  ,  78.  ,  98.2 ],
       [ 44.  ,  55.  ,  77.  ]])

In [30]:
# skip the header lines if it has
x = np.loadtxt('data.txt', skiprows=1)
x

array([[ 45.  ,  76.  ,  78.  ],
       [ 45.1 ,  77.  ,  88.  ],
       [ 45.  ,  54.6 ,  88.9 ],
       [ 67.  ,  55.  ,  66.  ],
       [  5.6 ,  78.  ,  98.  ],
       [  6.55,   7.88,  33.  ],
       [ 34.  ,  78.  ,  98.2 ],
       [ 44.  ,  55.  ,  77.  ]])

In [31]:
# use unpack parameter to load all columns into seperate arrays
a,b,c = np.loadtxt('data.txt', skiprows=1, unpack=True)
a

array([ 45.  ,  45.1 ,  45.  ,  67.  ,   5.6 ,   6.55,  34.  ,  44.  ])

In [32]:
b

array([ 76.  ,  77.  ,  54.6 ,  55.  ,  78.  ,   7.88,  78.  ,  55.  ])

In [33]:
c

array([ 78. ,  88. ,  88.9,  66. ,  98. ,  33. ,  98.2,  77. ])

## Loading CSV data with Pandas

In [23]:
import pandas as pd
df = pd.read_csv('pima-indians-diabetes.csv',header=0)

In [24]:
df.head()

Number of times pregnant  Plasma glucose concentration  \
0                         6                           148   
1                         1                            85   
2                         8                           183   
3                         1                            89   
4                         0                           137   

   Diastolic blood pressure  Triceps skin fold thickness  \
0                        72                           35   
1                        66                           29   
2                        64                            0   
3                        66                           23   
4                        40                           35   

   2-Hour serum insulin  Body mass index  Diabetes pedigree function  Ages  \
0                     0             33.6                       0.627    50   
1                     0             26.6                       0.351    31   
2                     0             23.3                       0.672    32   
3                    94             28.1                       0.167    21   
4                   168             43.1                       2.288    33   

   Class variable  
0               1  
1               0  
2               1  
3               0  
4               1

## Loading data from an URL or HTML

In [ ]:
df = pd.read_csv('http://conferences.ncl.ac.uk/sciprog/Presentations/temperature_profile.csv')

df.read_html('http://www.temperatureworld.com/ctable1.htm',skiprows=1)


## Loading data from MySQL and PostgresSQL

In [ ]:
import MySQLdb
conn = MySQLdb.connect("localhost", "user","pass","mydb")
df = pd.read_sql("SELECT * FROM mytable",conn)

In [ ]:
import psycopg2
conn = psycopg2.connect(host=“localhost”, user=“user”, password=“pass”, database=“mydb”)
df = pd.read_sql(“SELECT * FROM mytable”, conn)